// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwOTIPbebPh0eHZggGd2IL0TxNlCaeJk',
    appId: '1:506017127395:web:89ec28c6721319cca0ded6',
    messagingSenderId: '506017127395',
    projectId: 'carrental-bb936',
    authDomain: 'carrental-bb936.firebaseapp.com',
    storageBucket: 'carrental-bb936.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY6cqJWuA9DEwodOXBikIKDpKM57iI7nw',
    appId: '1:506017127395:android:0ac24147b948d866a0ded6',
    messagingSenderId: '506017127395',
    projectId: 'carrental-bb936',
    storageBucket: 'carrental-bb936.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp6zdG5upQTWDtq_ZWjmorhPnTklJMB0E',
    appId: '1:506017127395:ios:8d00fcd6bd9ab3bca0ded6',
    messagingSenderId: '506017127395',
    projectId: 'carrental-bb936',
    storageBucket: 'carrental-bb936.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp6zdG5upQTWDtq_ZWjmorhPnTklJMB0E',
    appId: '1:506017127395:ios:8d00fcd6bd9ab3bca0ded6',
    messagingSenderId: '506017127395',
    projectId: 'carrental-bb936',
    storageBucket: 'carrental-bb936.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkwOTIPbebPh0eHZggGd2IL0TxNlCaeJk',
    appId: '1:506017127395:web:9f275df6433b53fca0ded6',
    messagingSenderId: '506017127395',
    projectId: 'carrental-bb936',
    authDomain: 'carrental-bb936.firebaseapp.com',
    storageBucket: 'carrental-bb936.firebasestorage.app',
  );
}
